config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => "searchs#search"
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :followings,:followers
    end
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = book.id
    @comment.save
    #redirect_to book_path(book)
  end

  def destroy
    @books = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    #redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comment.html.erb
<table class = "table">
  <% books.book_comments.each do |book_comment| %>
    <tr>
      <td>
          <%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"50x50" %><br>
          <%= link_to user_path(book_comment.user) do %>
            <%= book_comment.user.name %>
          <% end %>
      </td>
      <td>
        <%= book_comment.comment %>
      </td>
      <% if book_comment.user_id == current_user.id %>
        <td>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment), method: :delete, class:"btn btn-sm btn-danger", remote: true %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/book_comments/create.js.erb
$("#comments_buttons_<%= @comment.book.id%>").html("<%= j(render 'book_comments/book_comment', { books: @comment.book }) %>")
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$("#comments_buttons_<%= @books.id%>").html("<%= j(render 'book_comments/book_comment', { books: @books }) %>")