config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => "searchs#search"
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :followings,:followers
    end
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  attachment :profile_image, destroy: false
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def self.looks(finders, words)
  	if finders == "forward_match"
      @users = User.where("name LIKE?","#{words}%")
    elsif finders == "backward_match"
      @users = User.where("name LIKE?","%#{words}")
    elsif finders == "perfect_match"
      @users = User.where("name LIKE?","#{words}")
    elsif finders == "partial_match"
      @users = User.where("name LIKE?","%#{words}%")
    else
      @users = User.all
    end
  end
  
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: { maximum:50 }
  validates :postal_code, presence: true
  validates :prefecture_code, presence: true
  validates :city, presence: true
  validates :street, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def followings
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"50x50" %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
        <% unless user == current_user %>
          <% if current_user.following?(user) %>
            <%= link_to user_relationships_path(user), method: :delete, remote: true do %>
              フォロー外す
            <% end %>
          <% else %>
            <%#= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
            <%= link_to user_relationships_path(user), method: :post, remote: true do %>
              フォローする
            <% end %>
          <% end %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"100x100" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to followings_user_path(user.id) do %>
        <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to followers_user_path(user.id) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>
<% if current_user == user %>
  <div class='row'>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  </div>
<% else %>
  <% if current_user.following?(user) %>
    <%= link_to user_relationships_path(user), method: :delete do %>
      フォロー外す
    <% end %>
  <% else %>
    <%= link_to user_relationships_path(user), method: :post do %>
      フォローする
    <% end %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name%>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class='row'>
  <div class='col-md-12'>
    <h2>Follower Users</h2>
    <table class = "table">
      <% if @user.followers.count == 0 %>
        <td>ユーザーはいません</td>
      <% else %>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.followers.each do |follow| %>
            <tr>
              <td>
                <%= attachment_image_tag follow, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"50x50" %>
              </td>
              <td>
                <%= follow.name %>
              </td>
              <td>
                フォロー数: <%= follow.followings.count %>
              </td>
              <td>
                フォロワー数: <%= follow.followers.count %>
              </td>
              <td>
                <%= link_to 'Show', user_path(follow), class: "user_#{follow.id}" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/users/followings.html.erb
<div class='row'>
  <div class='col-md-12'>
    <h2>Follow Users</h2>
    <table class = "table">
      <% if @user.followings.count == 0 %>
        <td>ユーザーはいません</td>
      <% else %>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.followings.each do |follow| %>
            <tr>
              <td>
                <%= attachment_image_tag follow, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"50x50" %>
              </td>
              <td>
                <%= follow.name %>
              </td>
              <td>
                フォロー数: <%= follow.followings.count %>
              </td>
              <td>
                フォロワー数: <%= follow.followers.count %>
              </td>
              <td>
                <%= link_to 'Show', user_path(follow), class: "user_#{follow.id}" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </table>
  </div>
</div

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>