config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => "searchs#search"
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :followings,:followers
    end
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @range = params[:range]
    @word = params[:word]
    if @range == "User"
      @users = User.looks(params[:finder], params[:word])
    else
      @books = Book.looks(params[:finder], params[:word])
    end
  end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/search.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12'>
      <table class = "table">
        <% if @range == "User" %>
          <div>
            Users search for "<%= @word %>"
          </div>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"50x50" %></td>
                <td><%= user.name %></td>
                <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
              </tr>
            <% end %>
          </tbody>
        <% else %>
          <div>
            Books search for "<%= @word %>"
          </div>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"50x50" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>